"""
Visualization utilities for ProcessGAN

Provides functions to visualize:
- Generated process graphs
- Adjacency matrices
- Trace sequences
- Training metrics
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import ListedColormap
import networkx as nx
from typing import List, Dict, Optional, Tuple


class ProcessGraphVisualizer:
    """Visualize process graphs generated by ProcessGAN"""

    def __init__(self, activity_decoder: Dict[int, str], flow_decoder: Dict[int, str]):
        """
        Args:
            activity_decoder: Mapping from activity indices to names
            flow_decoder: Mapping from flow type indices to names
        """
        self.activity_decoder = activity_decoder
        self.flow_decoder = flow_decoder

        # Color scheme for different flow types
        self.flow_colors = {
            'SEQUENCE': '#2E86AB',      # Blue
            'PARALLEL': '#A23B72',       # Purple
            'LOOP': '#F18F01',           # Orange
            'CHOICE': '#C73E1D',         # Red
            'SKIP': '#6A994E'            # Green
        }

        # Node colors
        self.node_colors = {
            'Start': '#90EE90',          # Light green
            'End': '#FFB6C6',            # Light red
            'default': '#87CEEB'         # Sky blue
        }

    def visualize_graph(self, adjacency: np.ndarray, nodes: np.ndarray,
                       title: str = "Generated Process Graph",
                       figsize: Tuple[int, int] = (12, 8),
                       save_path: Optional[str] = None) -> plt.Figure:
        """
        Visualize a process graph using NetworkX

        Args:
            adjacency: Adjacency matrix (max_activities, max_activities, flow_types)
            nodes: Node feature matrix (max_activities, activity_types)
            title: Plot title
            figsize: Figure size
            save_path: Optional path to save the figure

        Returns:
            Matplotlib figure
        """
        # Decode adjacency and nodes
        if len(adjacency.shape) == 3:
            # One-hot encoded: (N, N, F)
            adj_indices = np.argmax(adjacency, axis=-1)
        else:
            adj_indices = adjacency

        if len(nodes.shape) == 2:
            # One-hot encoded: (N, A)
            node_indices = np.argmax(nodes, axis=-1)
        else:
            node_indices = nodes

        # Create directed graph
        G = nx.DiGraph()

        # Add nodes with activity labels
        activity_labels = {}
        node_color_list = []
        active_nodes = []

        for i in range(len(node_indices)):
            activity_idx = node_indices[i]
            if activity_idx in self.activity_decoder:
                activity_name = self.activity_decoder[activity_idx]
                # Skip padding nodes
                if activity_name not in ['PAD', '<PAD>', '']:
                    G.add_node(i)
                    activity_labels[i] = activity_name
                    active_nodes.append(i)

                    # Set node color
                    if 'Start' in activity_name or activity_name == 'S':
                        node_color_list.append(self.node_colors['Start'])
                    elif 'End' in activity_name or activity_name == 'E':
                        node_color_list.append(self.node_colors['End'])
                    else:
                        node_color_list.append(self.node_colors['default'])

        # Add edges with flow types
        edge_colors = []
        edge_labels = {}
        edge_styles = []

        for i in active_nodes:
            for j in active_nodes:
                flow_idx = adj_indices[i, j]
                if flow_idx > 0 and flow_idx in self.flow_decoder:
                    flow_type = self.flow_decoder[flow_idx]
                    G.add_edge(i, j)
                    edge_labels[(i, j)] = flow_type
                    edge_colors.append(self.flow_colors.get(flow_type, '#888888'))

                    # Different line styles for different flow types
                    if flow_type == 'LOOP':
                        edge_styles.append('dashed')
                    elif flow_type == 'CHOICE':
                        edge_styles.append('dotted')
                    else:
                        edge_styles.append('solid')

        # Create figure
        fig, ax = plt.subplots(figsize=figsize)

        # Layout: hierarchical for process flows
        try:
            # Try hierarchical layout
            pos = self._hierarchical_layout(G, active_nodes)
        except:
            # Fall back to spring layout
            pos = nx.spring_layout(G, k=2, iterations=50, seed=42)

        # Draw nodes
        nx.draw_networkx_nodes(G, pos,
                              node_color=node_color_list,
                              node_size=2000,
                              alpha=0.9,
                              ax=ax)

        # Draw edges with different styles
        for (u, v), style in zip(G.edges(), edge_styles):
            edge_color = edge_colors[list(G.edges()).index((u, v))]
            nx.draw_networkx_edges(G, pos, [(u, v)],
                                  edge_color=[edge_color],
                                  style=style,
                                  width=2.5,
                                  alpha=0.7,
                                  arrowsize=20,
                                  arrowstyle='->',
                                  connectionstyle='arc3,rad=0.1',
                                  ax=ax)

        # Draw labels
        nx.draw_networkx_labels(G, pos, activity_labels,
                               font_size=9,
                               font_weight='bold',
                               ax=ax)

        # Draw edge labels
        nx.draw_networkx_edge_labels(G, pos, edge_labels,
                                     font_size=7,
                                     font_color='#333333',
                                     ax=ax)

        # Create legend
        legend_elements = [
            mpatches.Patch(color=color, label=flow_type)
            for flow_type, color in self.flow_colors.items()
            if flow_type in edge_labels.values()
        ]
        ax.legend(handles=legend_elements, loc='upper right', fontsize=10)

        ax.set_title(title, fontsize=14, fontweight='bold', pad=20)
        ax.axis('off')
        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')

        return fig

    def _hierarchical_layout(self, G: nx.DiGraph, active_nodes: List[int]) -> Dict:
        """Create hierarchical layout for process graph"""
        # Find start nodes (no incoming edges)
        start_nodes = [n for n in G.nodes() if G.in_degree(n) == 0]

        if not start_nodes:
            # If no start node, use the first node
            start_nodes = [active_nodes[0]]

        # BFS to assign levels
        levels = {}
        queue = [(n, 0) for n in start_nodes]
        visited = set()

        while queue:
            node, level = queue.pop(0)
            if node in visited:
                continue
            visited.add(node)
            levels[node] = level

            for successor in G.successors(node):
                if successor not in visited:
                    queue.append((successor, level + 1))

        # Assign positions based on levels
        pos = {}
        level_nodes = {}

        for node, level in levels.items():
            if level not in level_nodes:
                level_nodes[level] = []
            level_nodes[level].append(node)

        max_level = max(levels.values()) if levels else 0

        for level, nodes in level_nodes.items():
            x = level / (max_level + 1) if max_level > 0 else 0.5
            for i, node in enumerate(nodes):
                y = (i + 1) / (len(nodes) + 1)
                pos[node] = (x, y)

        return pos

    def visualize_adjacency_matrix(self, adjacency: np.ndarray,
                                   node_labels: Optional[List[str]] = None,
                                   title: str = "Adjacency Matrix",
                                   figsize: Tuple[int, int] = (10, 8),
                                   save_path: Optional[str] = None) -> plt.Figure:
        """
        Visualize adjacency matrix as heatmap

        Args:
            adjacency: Adjacency matrix
            node_labels: Optional labels for nodes
            title: Plot title
            figsize: Figure size
            save_path: Optional path to save

        Returns:
            Matplotlib figure
        """
        # Get flow type indices
        if len(adjacency.shape) == 3:
            adj_indices = np.argmax(adjacency, axis=-1)
        else:
            adj_indices = adjacency

        # Create figure
        fig, ax = plt.subplots(figsize=figsize)

        # Custom colormap for flow types
        n_flow_types = len(self.flow_decoder)
        colors = ['white'] + list(self.flow_colors.values())[:n_flow_types]
        cmap = ListedColormap(colors)

        # Plot heatmap
        im = ax.imshow(adj_indices, cmap=cmap, aspect='auto', vmin=0, vmax=n_flow_types)

        # Set ticks
        if node_labels:
            ax.set_xticks(np.arange(len(node_labels)))
            ax.set_yticks(np.arange(len(node_labels)))
            ax.set_xticklabels(node_labels, rotation=45, ha='right')
            ax.set_yticklabels(node_labels)

        # Add colorbar
        cbar = plt.colorbar(im, ax=ax, ticks=np.arange(n_flow_types + 1))
        cbar.set_label('Flow Type', rotation=270, labelpad=20)
        cbar.ax.set_yticklabels(['None'] + list(self.flow_decoder.values()))

        ax.set_title(title, fontsize=14, fontweight='bold', pad=20)
        ax.set_xlabel('Target Activity')
        ax.set_ylabel('Source Activity')

        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')

        return fig

    def visualize_trace(self, trace: List[str],
                       title: str = "Process Trace",
                       figsize: Tuple[int, int] = (14, 2),
                       save_path: Optional[str] = None) -> plt.Figure:
        """
        Visualize a single trace as a sequence

        Args:
            trace: List of activity names
            title: Plot title
            figsize: Figure size
            save_path: Optional path to save

        Returns:
            Matplotlib figure
        """
        fig, ax = plt.subplots(figsize=figsize)

        n_activities = len(trace)

        for i, activity in enumerate(trace):
            # Node color
            if 'Start' in activity or activity == 'S':
                color = self.node_colors['Start']
            elif 'End' in activity or activity == 'E':
                color = self.node_colors['End']
            else:
                color = self.node_colors['default']

            # Draw box
            rect = mpatches.FancyBboxPatch((i, 0), 0.8, 0.6,
                                          boxstyle="round,pad=0.05",
                                          facecolor=color,
                                          edgecolor='black',
                                          linewidth=2)
            ax.add_patch(rect)

            # Add text
            ax.text(i + 0.4, 0.3, activity,
                   ha='center', va='center',
                   fontsize=10, fontweight='bold')

            # Draw arrow to next activity
            if i < n_activities - 1:
                ax.arrow(i + 0.8, 0.3, 0.15, 0,
                        head_width=0.15, head_length=0.05,
                        fc='black', ec='black')

        ax.set_xlim(-0.2, n_activities)
        ax.set_ylim(-0.2, 0.8)
        ax.set_aspect('equal')
        ax.axis('off')
        ax.set_title(title, fontsize=14, fontweight='bold', pad=20)

        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')

        return fig

    def visualize_batch(self, adjacency_batch: np.ndarray,
                       nodes_batch: np.ndarray,
                       n_samples: int = 4,
                       figsize: Tuple[int, int] = (16, 12),
                       save_path: Optional[str] = None) -> plt.Figure:
        """
        Visualize multiple generated graphs in a grid

        Args:
            adjacency_batch: Batch of adjacency matrices
            nodes_batch: Batch of node features
            n_samples: Number of samples to visualize
            figsize: Figure size
            save_path: Optional path to save

        Returns:
            Matplotlib figure
        """
        n_samples = min(n_samples, len(adjacency_batch))
        n_cols = 2
        n_rows = (n_samples + n_cols - 1) // n_cols

        fig = plt.figure(figsize=figsize)

        for i in range(n_samples):
            ax = fig.add_subplot(n_rows, n_cols, i + 1)
            plt.sca(ax)

            # Create temporary figure for single graph
            temp_fig = self.visualize_graph(
                adjacency_batch[i],
                nodes_batch[i],
                title=f"Generated Graph {i+1}",
                figsize=(6, 4)
            )

            # Copy to subplot
            temp_ax = temp_fig.axes[0]
            for artist in temp_ax.get_children():
                if hasattr(artist, 'get_paths'):
                    ax.add_artist(artist)

            ax.set_xlim(temp_ax.get_xlim())
            ax.set_ylim(temp_ax.get_ylim())
            ax.axis('off')
            ax.set_title(f"Sample {i+1}", fontsize=12, fontweight='bold')

            plt.close(temp_fig)

        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')

        return fig


def plot_training_metrics(losses_d: List[float],
                         losses_g: List[float],
                         rewards: List[float],
                         figsize: Tuple[int, int] = (15, 5),
                         save_path: Optional[str] = None) -> plt.Figure:
    """
    Plot training metrics over time

    Args:
        losses_d: Discriminator losses
        losses_g: Generator losses
        rewards: Reward values
        figsize: Figure size
        save_path: Optional path to save

    Returns:
        Matplotlib figure
    """
    fig, axes = plt.subplots(1, 3, figsize=figsize)

    # Discriminator loss
    axes[0].plot(losses_d, color='#2E86AB', linewidth=2)
    axes[0].set_title('Discriminator Loss', fontsize=12, fontweight='bold')
    axes[0].set_xlabel('Iteration')
    axes[0].set_ylabel('Loss')
    axes[0].grid(True, alpha=0.3)

    # Generator loss
    axes[1].plot(losses_g, color='#A23B72', linewidth=2)
    axes[1].set_title('Generator Loss', fontsize=12, fontweight='bold')
    axes[1].set_xlabel('Iteration')
    axes[1].set_ylabel('Loss')
    axes[1].grid(True, alpha=0.3)

    # Rewards
    axes[2].plot(rewards, color='#F18F01', linewidth=2)
    axes[2].set_title('Average Reward', fontsize=12, fontweight='bold')
    axes[2].set_xlabel('Iteration')
    axes[2].set_ylabel('Reward')
    axes[2].grid(True, alpha=0.3)
    axes[2].axhline(y=0.7, color='green', linestyle='--', alpha=0.5, label='Target')
    axes[2].legend()

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')

    return fig


def plot_reward_components(validity: List[float],
                          fitness: List[float],
                          conformance: List[float],
                          diversity: List[float],
                          figsize: Tuple[int, int] = (12, 6),
                          save_path: Optional[str] = None) -> plt.Figure:
    """
    Plot individual reward components

    Args:
        validity: Validity scores
        fitness: Fitness scores
        conformance: Conformance scores
        diversity: Diversity scores
        figsize: Figure size
        save_path: Optional path to save

    Returns:
        Matplotlib figure
    """
    fig, ax = plt.subplots(figsize=figsize)

    iterations = range(len(validity))

    ax.plot(iterations, validity, label='Validity', color='#2E86AB', linewidth=2)
    ax.plot(iterations, fitness, label='Fitness', color='#A23B72', linewidth=2)
    ax.plot(iterations, conformance, label='Conformance', color='#F18F01', linewidth=2)
    ax.plot(iterations, diversity, label='Diversity', color='#6A994E', linewidth=2)

    ax.set_title('Reward Components Over Time', fontsize=14, fontweight='bold')
    ax.set_xlabel('Iteration')
    ax.set_ylabel('Score')
    ax.legend(loc='best', fontsize=11)
    ax.grid(True, alpha=0.3)
    ax.set_ylim([0, 1.05])

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')

    return fig
